//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatAAC.Lang {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ChatAAC.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        public static string SelectedPictogramHelpText {
            get {
                return ResourceManager.GetString("SelectedPictogramHelpText", resourceCulture);
            }
        }
        
        public static string ClearTextButton {
            get {
                return ResourceManager.GetString("ClearTextButton", resourceCulture);
            }
        }
        
        public static string TenseLabel {
            get {
                return ResourceManager.GetString("TenseLabel", resourceCulture);
            }
        }
        
        public static string PastTense {
            get {
                return ResourceManager.GetString("PastTense", resourceCulture);
            }
        }
        
        public static string FutureTense {
            get {
                return ResourceManager.GetString("FutureTense", resourceCulture);
            }
        }
        
        public static string FormLabel {
            get {
                return ResourceManager.GetString("FormLabel", resourceCulture);
            }
        }
        
        public static string DeclarativeForm {
            get {
                return ResourceManager.GetString("DeclarativeForm", resourceCulture);
            }
        }
        
        public static string QuestionForm {
            get {
                return ResourceManager.GetString("QuestionForm", resourceCulture);
            }
        }
        
        public static string ClearTextButtonAutomation {
            get {
                return ResourceManager.GetString("ClearTextButtonAutomation", resourceCulture);
            }
        }
        
        public static string PastTenseAutomation {
            get {
                return ResourceManager.GetString("PastTenseAutomation", resourceCulture);
            }
        }
        
        public static string PresentTenseAutomation {
            get {
                return ResourceManager.GetString("PresentTenseAutomation", resourceCulture);
            }
        }
        
        public static string PresentTense {
            get {
                return ResourceManager.GetString("PresentTense", resourceCulture);
            }
        }
        
        public static string DeclarativeFormAutomation {
            get {
                return ResourceManager.GetString("DeclarativeFormAutomation", resourceCulture);
            }
        }
        
        public static string QuestionFormAutomation {
            get {
                return ResourceManager.GetString("QuestionFormAutomation", resourceCulture);
            }
        }
        
        public static string BackButtonAutomation {
            get {
                return ResourceManager.GetString("BackButtonAutomation", resourceCulture);
            }
        }
        
        public static string BackButton {
            get {
                return ResourceManager.GetString("BackButton", resourceCulture);
            }
        }
        
        public static string FutureTenseAutomation {
            get {
                return ResourceManager.GetString("FutureTenseAutomation", resourceCulture);
            }
        }
        
        public static string HistoryButtonAutomation {
            get {
                return ResourceManager.GetString("HistoryButtonAutomation", resourceCulture);
            }
        }
        
        public static string HistoryButton {
            get {
                return ResourceManager.GetString("HistoryButton", resourceCulture);
            }
        }
        
        public static string SettingsButtonAutomation {
            get {
                return ResourceManager.GetString("SettingsButtonAutomation", resourceCulture);
            }
        }
        
        public static string SettingsButton {
            get {
                return ResourceManager.GetString("SettingsButton", resourceCulture);
            }
        }
        
        public static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        public static string PreviousBoardAutomation {
            get {
                return ResourceManager.GetString("PreviousBoardAutomation", resourceCulture);
            }
        }
        
        public static string PreviousBoard {
            get {
                return ResourceManager.GetString("PreviousBoard", resourceCulture);
            }
        }
        
        public static string NextBoardAutomation {
            get {
                return ResourceManager.GetString("NextBoardAutomation", resourceCulture);
            }
        }
        
        public static string NextBoard {
            get {
                return ResourceManager.GetString("NextBoard", resourceCulture);
            }
        }
        
        public static string SettingsWindowTitle {
            get {
                return ResourceManager.GetString("SettingsWindowTitle", resourceCulture);
            }
        }
        
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        public static string GeneralTab {
            get {
                return ResourceManager.GetString("GeneralTab", resourceCulture);
            }
        }
        
        public static string OllamaAddressLabel {
            get {
                return ResourceManager.GetString("OllamaAddressLabel", resourceCulture);
            }
        }
        
        public static string OllamaAddressAutomation {
            get {
                return ResourceManager.GetString("OllamaAddressAutomation", resourceCulture);
            }
        }
        
        public static string SelectModelLabel {
            get {
                return ResourceManager.GetString("SelectModelLabel", resourceCulture);
            }
        }
        
        public static string ProgramLanguageLabel {
            get {
                return ResourceManager.GetString("ProgramLanguageLabel", resourceCulture);
            }
        }
        
        public static string BoardsTab {
            get {
                return ResourceManager.GetString("BoardsTab", resourceCulture);
            }
        }
        
        public static string IncludeSexSymbols {
            get {
                return ResourceManager.GetString("IncludeSexSymbols", resourceCulture);
            }
        }
        
        public static string IncludeViolenceSymbols {
            get {
                return ResourceManager.GetString("IncludeViolenceSymbols", resourceCulture);
            }
        }
        
        public static string DefaultBoardLabel {
            get {
                return ResourceManager.GetString("DefaultBoardLabel", resourceCulture);
            }
        }
        
        public static string AACBoardFilesLabel {
            get {
                return ResourceManager.GetString("AACBoardFilesLabel", resourceCulture);
            }
        }
        
        public static string AddFileButton {
            get {
                return ResourceManager.GetString("AddFileButton", resourceCulture);
            }
        }
        
        public static string BoardPathTooltip {
            get {
                return ResourceManager.GetString("BoardPathTooltip", resourceCulture);
            }
        }
        
        public static string RemoveButton {
            get {
                return ResourceManager.GetString("RemoveButton", resourceCulture);
            }
        }
        
        public static string RemoveButtonAutomation {
            get {
                return ResourceManager.GetString("RemoveButtonAutomation", resourceCulture);
            }
        }
        
        public static string DisplayTab {
            get {
                return ResourceManager.GetString("DisplayTab", resourceCulture);
            }
        }
        
        public static string FontSizeLabel {
            get {
                return ResourceManager.GetString("FontSizeLabel", resourceCulture);
            }
        }
        
        public static string ButtonSizeLabel {
            get {
                return ResourceManager.GetString("ButtonSizeLabel", resourceCulture);
            }
        }
        
        public static string ShowSymbolsLabel {
            get {
                return ResourceManager.GetString("ShowSymbolsLabel", resourceCulture);
            }
        }
        
        public static string AdvancedTab {
            get {
                return ResourceManager.GetString("AdvancedTab", resourceCulture);
            }
        }
        
        public static string CacheDirectoryLabel {
            get {
                return ResourceManager.GetString("CacheDirectoryLabel", resourceCulture);
            }
        }
        
        public static string ClearCacheButton {
            get {
                return ResourceManager.GetString("ClearCacheButton", resourceCulture);
            }
        }
        
        public static string BackupSettingsLabel {
            get {
                return ResourceManager.GetString("BackupSettingsLabel", resourceCulture);
            }
        }
        
        public static string ExportSettingsButton {
            get {
                return ResourceManager.GetString("ExportSettingsButton", resourceCulture);
            }
        }
        
        public static string ImportSettingsButton {
            get {
                return ResourceManager.GetString("ImportSettingsButton", resourceCulture);
            }
        }
        
        public static string AboutButton {
            get {
                return ResourceManager.GetString("AboutButton", resourceCulture);
            }
        }
        
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        public static string AboutWindowTitle {
            get {
                return ResourceManager.GetString("AboutWindowTitle", resourceCulture);
            }
        }
        
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        public static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        public static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        public static string AboutAuthor {
            get {
                return ResourceManager.GetString("AboutAuthor", resourceCulture);
            }
        }
        
        public static string AboutContact {
            get {
                return ResourceManager.GetString("AboutContact", resourceCulture);
            }
        }
        
        public static string AboutArasaacTitle {
            get {
                return ResourceManager.GetString("AboutArasaacTitle", resourceCulture);
            }
        }
        
        public static string AboutArasaacDescription {
            get {
                return ResourceManager.GetString("AboutArasaacDescription", resourceCulture);
            }
        }
        
        public static string AboutLicensesTitle {
            get {
                return ResourceManager.GetString("AboutLicensesTitle", resourceCulture);
            }
        }
        
        public static string AboutLicensesDescription {
            get {
                return ResourceManager.GetString("AboutLicensesDescription", resourceCulture);
            }
        }
        
        public static string AboutCloseButton {
            get {
                return ResourceManager.GetString("AboutCloseButton", resourceCulture);
            }
        }
        
        public static string AboutCloseButtonAutomation {
            get {
                return ResourceManager.GetString("AboutCloseButtonAutomation", resourceCulture);
            }
        }
    }
}
