//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatAAC.Lang {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ChatAAC.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        public static string SelectedPictogramHelpText {
            get {
                return ResourceManager.GetString("SelectedPictogramHelpText", resourceCulture);
            }
        }
        
        public static string ClearTextButton {
            get {
                return ResourceManager.GetString("ClearTextButton", resourceCulture);
            }
        }
        
        public static string TenseLabel {
            get {
                return ResourceManager.GetString("TenseLabel", resourceCulture);
            }
        }
        
        public static string PastTense {
            get {
                return ResourceManager.GetString("PastTense", resourceCulture);
            }
        }
        
        public static string FutureTense {
            get {
                return ResourceManager.GetString("FutureTense", resourceCulture);
            }
        }
        
        public static string FormLabel {
            get {
                return ResourceManager.GetString("FormLabel", resourceCulture);
            }
        }
        
        public static string DeclarativeForm {
            get {
                return ResourceManager.GetString("DeclarativeForm", resourceCulture);
            }
        }
        
        public static string QuestionForm {
            get {
                return ResourceManager.GetString("QuestionForm", resourceCulture);
            }
        }
        
        public static string ClearTextButtonAutomation {
            get {
                return ResourceManager.GetString("ClearTextButtonAutomation", resourceCulture);
            }
        }
        
        public static string PastTenseAutomation {
            get {
                return ResourceManager.GetString("PastTenseAutomation", resourceCulture);
            }
        }
        
        public static string PresentTenseAutomation {
            get {
                return ResourceManager.GetString("PresentTenseAutomation", resourceCulture);
            }
        }
        
        public static string PresentTense {
            get {
                return ResourceManager.GetString("PresentTense", resourceCulture);
            }
        }
        
        public static string DeclarativeFormAutomation {
            get {
                return ResourceManager.GetString("DeclarativeFormAutomation", resourceCulture);
            }
        }
        
        public static string QuestionFormAutomation {
            get {
                return ResourceManager.GetString("QuestionFormAutomation", resourceCulture);
            }
        }
        
        public static string BackButtonAutomation {
            get {
                return ResourceManager.GetString("BackButtonAutomation", resourceCulture);
            }
        }
        
        public static string BackButton {
            get {
                return ResourceManager.GetString("BackButton", resourceCulture);
            }
        }
        
        public static string FutureTenseAutomation {
            get {
                return ResourceManager.GetString("FutureTenseAutomation", resourceCulture);
            }
        }
        
        public static string HistoryButtonAutomation {
            get {
                return ResourceManager.GetString("HistoryButtonAutomation", resourceCulture);
            }
        }
        
        public static string HistoryButton {
            get {
                return ResourceManager.GetString("HistoryButton", resourceCulture);
            }
        }
        
        public static string SettingsButtonAutomation {
            get {
                return ResourceManager.GetString("SettingsButtonAutomation", resourceCulture);
            }
        }
        
        public static string SettingsButton {
            get {
                return ResourceManager.GetString("SettingsButton", resourceCulture);
            }
        }
        
        public static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        public static string PreviousBoardAutomation {
            get {
                return ResourceManager.GetString("PreviousBoardAutomation", resourceCulture);
            }
        }
        
        public static string PreviousBoard {
            get {
                return ResourceManager.GetString("PreviousBoard", resourceCulture);
            }
        }
        
        public static string NextBoardAutomation {
            get {
                return ResourceManager.GetString("NextBoardAutomation", resourceCulture);
            }
        }
        
        public static string NextBoard {
            get {
                return ResourceManager.GetString("NextBoard", resourceCulture);
            }
        }
        
        public static string SettingsWindowTitle {
            get {
                return ResourceManager.GetString("SettingsWindowTitle", resourceCulture);
            }
        }
        
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        public static string GeneralTab {
            get {
                return ResourceManager.GetString("GeneralTab", resourceCulture);
            }
        }
        
        public static string OllamaAddressLabel {
            get {
                return ResourceManager.GetString("OllamaAddressLabel", resourceCulture);
            }
        }
        
        public static string OllamaAddressAutomation {
            get {
                return ResourceManager.GetString("OllamaAddressAutomation", resourceCulture);
            }
        }
        
        public static string SelectModelLabel {
            get {
                return ResourceManager.GetString("SelectModelLabel", resourceCulture);
            }
        }
        
        public static string ProgramLanguageLabel {
            get {
                return ResourceManager.GetString("ProgramLanguageLabel", resourceCulture);
            }
        }
        
        public static string BoardsTab {
            get {
                return ResourceManager.GetString("BoardsTab", resourceCulture);
            }
        }
        
        public static string IncludeSexSymbols {
            get {
                return ResourceManager.GetString("IncludeSexSymbols", resourceCulture);
            }
        }
        
        public static string IncludeViolenceSymbols {
            get {
                return ResourceManager.GetString("IncludeViolenceSymbols", resourceCulture);
            }
        }
        
        public static string DefaultBoardLabel {
            get {
                return ResourceManager.GetString("DefaultBoardLabel", resourceCulture);
            }
        }
        
        public static string AACBoardFilesLabel {
            get {
                return ResourceManager.GetString("AACBoardFilesLabel", resourceCulture);
            }
        }
        
        public static string AddFileButton {
            get {
                return ResourceManager.GetString("AddFileButton", resourceCulture);
            }
        }
        
        public static string BoardPathTooltip {
            get {
                return ResourceManager.GetString("BoardPathTooltip", resourceCulture);
            }
        }
        
        public static string RemoveButton {
            get {
                return ResourceManager.GetString("RemoveButton", resourceCulture);
            }
        }
        
        public static string RemoveButtonAutomation {
            get {
                return ResourceManager.GetString("RemoveButtonAutomation", resourceCulture);
            }
        }
        
        public static string DisplayTab {
            get {
                return ResourceManager.GetString("DisplayTab", resourceCulture);
            }
        }
        
        public static string FontSizeLabel {
            get {
                return ResourceManager.GetString("FontSizeLabel", resourceCulture);
            }
        }
        
        public static string ButtonSizeLabel {
            get {
                return ResourceManager.GetString("ButtonSizeLabel", resourceCulture);
            }
        }
        
        public static string ShowSymbolsLabel {
            get {
                return ResourceManager.GetString("ShowSymbolsLabel", resourceCulture);
            }
        }
        
        public static string AdvancedTab {
            get {
                return ResourceManager.GetString("AdvancedTab", resourceCulture);
            }
        }
        
        public static string CacheDirectoryLabel {
            get {
                return ResourceManager.GetString("CacheDirectoryLabel", resourceCulture);
            }
        }
        
        public static string ClearCacheButton {
            get {
                return ResourceManager.GetString("ClearCacheButton", resourceCulture);
            }
        }
        
        public static string BackupSettingsLabel {
            get {
                return ResourceManager.GetString("BackupSettingsLabel", resourceCulture);
            }
        }
        
        public static string ExportSettingsButton {
            get {
                return ResourceManager.GetString("ExportSettingsButton", resourceCulture);
            }
        }
        
        public static string ImportSettingsButton {
            get {
                return ResourceManager.GetString("ImportSettingsButton", resourceCulture);
            }
        }
        
        public static string AboutButton {
            get {
                return ResourceManager.GetString("AboutButton", resourceCulture);
            }
        }
        
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        public static string AboutWindowTitle {
            get {
                return ResourceManager.GetString("AboutWindowTitle", resourceCulture);
            }
        }
        
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        public static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        public static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        public static string AboutAuthor {
            get {
                return ResourceManager.GetString("AboutAuthor", resourceCulture);
            }
        }
        
        public static string AboutContact {
            get {
                return ResourceManager.GetString("AboutContact", resourceCulture);
            }
        }
        
        public static string AboutArasaacTitle {
            get {
                return ResourceManager.GetString("AboutArasaacTitle", resourceCulture);
            }
        }
        
        public static string AboutArasaacDescription {
            get {
                return ResourceManager.GetString("AboutArasaacDescription", resourceCulture);
            }
        }
        
        public static string AboutLicensesTitle {
            get {
                return ResourceManager.GetString("AboutLicensesTitle", resourceCulture);
            }
        }
        
        public static string AboutLicensesDescription {
            get {
                return ResourceManager.GetString("AboutLicensesDescription", resourceCulture);
            }
        }
        
        public static string AboutCloseButton {
            get {
                return ResourceManager.GetString("AboutCloseButton", resourceCulture);
            }
        }
        
        public static string AboutCloseButtonAutomation {
            get {
                return ResourceManager.GetString("AboutCloseButtonAutomation", resourceCulture);
            }
        }
        
        public static string SortNewestToOldestButton {
            get {
                return ResourceManager.GetString("SortNewestToOldestButton", resourceCulture);
            }
        }
        
        public static string SpeakSelectedEntryButton {
            get {
                return ResourceManager.GetString("SpeakSelectedEntryButton", resourceCulture);
            }
        }
        
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        public static string HistoryWindowTitle {
            get {
                return ResourceManager.GetString("HistoryWindowTitle", resourceCulture);
            }
        }
        
        public static string SortOldestToNewestButton {
            get {
                return ResourceManager.GetString("SortOldestToNewestButton", resourceCulture);
            }
        }
        
        public static string SortFavoritesButton {
            get {
                return ResourceManager.GetString("SortFavoritesButton", resourceCulture);
            }
        }
        
        public static string FavoriteButton {
            get {
                return ResourceManager.GetString("FavoriteButton", resourceCulture);
            }
        }
        
        public static string BoardLoaderService_LoadObzFileAsync_root_obf_file_not_found_in_the_OBZ_package_ {
            get {
                return ResourceManager.GetString("BoardLoaderService_LoadObzFileAsync_root_obf_file_not_found_in_the_OBZ_package_", resourceCulture);
            }
        }
        
        public static string ClipboardService_CopyToClipboard_Clipboard_is_not_available_ {
            get {
                return ResourceManager.GetString("ClipboardService_CopyToClipboard_Clipboard_is_not_available_", resourceCulture);
            }
        }
        
        public static string LinuxTtsService_SpeakAsync_Błąd_podczas_odczytywania_tekstu___0_ {
            get {
                return ResourceManager.GetString("LinuxTtsService_SpeakAsync_Błąd_podczas_odczytywania_tekstu___0_", resourceCulture);
            }
        }
        
        public static string MainViewModel_OpenHistoryWindow_Error_opening_history_window___0_ {
            get {
                return ResourceManager.GetString("MainViewModel_OpenHistoryWindow_Error_opening_history_window___0_", resourceCulture);
            }
        }
        
        public static string MainViewModel_LoadInitialFileAsync_Błąd_podczas_wczytywania_pliku_początkowego___0_ {
            get {
                return ResourceManager.GetString("MainViewModel_LoadInitialFileAsync_Błąd_podczas_wczytywania_pliku_początkowego___" +
                        "0_", resourceCulture);
            }
        }
        
        public static string MainViewModel_LoadNextBoardAsync_Historia_jest_pusta_ {
            get {
                return ResourceManager.GetString("MainViewModel_LoadNextBoardAsync_Historia_jest_pusta_", resourceCulture);
            }
        }
        
        public static string MainViewModel_LoadNextBoardAsync_Brak_kolejnych_tablic_w_historii_ {
            get {
                return ResourceManager.GetString("MainViewModel_LoadNextBoardAsync_Brak_kolejnych_tablic_w_historii_", resourceCulture);
            }
        }
        
        public static string MainViewModel_LoadPreviousBoardAsync_Brak_poprzednich_tablic_w_historii_ {
            get {
                return ResourceManager.GetString("MainViewModel_LoadPreviousBoardAsync_Brak_poprzednich_tablic_w_historii_", resourceCulture);
            }
        }
        
        public static string MainViewModel_OnButtonClickedAsync_Kliknięto_przycisk___0_ {
            get {
                return ResourceManager.GetString("MainViewModel_OnButtonClickedAsync_Kliknięto_przycisk___0_", resourceCulture);
            }
        }
        
        public static string MainViewModel_UpdateConstructedSentence_Constructed_sentence___0_ {
            get {
                return ResourceManager.GetString("MainViewModel_UpdateConstructedSentence_Constructed_sentence___0_", resourceCulture);
            }
        }
        
        public static string MainViewModel_SpeakConstructedSentence_Spoken_sentence___0_ {
            get {
                return ResourceManager.GetString("MainViewModel_SpeakConstructedSentence_Spoken_sentence___0_", resourceCulture);
            }
        }
        
        public static string MainViewModel_SpeakConstructedSentence_Error_speaking_text___0_ {
            get {
                return ResourceManager.GetString("MainViewModel_SpeakConstructedSentence_Error_speaking_text___0_", resourceCulture);
            }
        }
        
        public static string MainViewModel_SendToAiAsync_Sending_query___0_ {
            get {
                return ResourceManager.GetString("MainViewModel_SendToAiAsync_Sending_query___0_", resourceCulture);
            }
        }
        
        public static string MainWindowGeneratingResponse {
            get {
                return ResourceManager.GetString("MainWindowGeneratingResponse", resourceCulture);
            }
        }
        
        public static string MainViewModel_SendToAiAsync_AI_Response___0_ {
            get {
                return ResourceManager.GetString("MainViewModel_SendToAiAsync_AI_Response___0_", resourceCulture);
            }
        }
        
        public static string MainViewModel_SpeakAiResponseAsync_Spoken_AI_response___0_ {
            get {
                return ResourceManager.GetString("MainViewModel_SpeakAiResponseAsync_Spoken_AI_response___0_", resourceCulture);
            }
        }
        
        public static string BoardLoaderService_LoadObzFileAsync_manifest_json_file_not_found_in_the_OBZ_package_ {
            get {
                return ResourceManager.GetString("BoardLoaderService_LoadObzFileAsync_manifest_json_file_not_found_in_the_OBZ_packa" +
                        "ge_", resourceCulture);
            }
        }
        
        public static string MainViewModel_SpeakAiResponseAsync_Error_speaking_AI_response___0_ {
            get {
                return ResourceManager.GetString("MainViewModel_SpeakAiResponseAsync_Error_speaking_AI_response___0_", resourceCulture);
            }
        }
        
        public static string MainViewModel_OpenSettings_Error_opening_settings_window___0_ {
            get {
                return ResourceManager.GetString("MainViewModel_OpenSettings_Error_opening_settings_window___0_", resourceCulture);
            }
        }
        
        public static string MacTtsService_SpeakAsync_Błąd_podczas_odczytywania_tekstu___0_ {
            get {
                return ResourceManager.GetString("MacTtsService_SpeakAsync_Błąd_podczas_odczytywania_tekstu___0_", resourceCulture);
            }
        }
        
        public static string MacTtsService_SpeakAsync_Tekst_do_odczytania_nie_może_być_pusty_ {
            get {
                return ResourceManager.GetString("MacTtsService_SpeakAsync_Tekst_do_odczytania_nie_może_być_pusty_", resourceCulture);
            }
        }
        
        public static string MacTtsService_SpeakAsync_NotSupported {
            get {
                return ResourceManager.GetString("MacTtsService_SpeakAsync_NotSupported", resourceCulture);
            }
        }
        
        public static string MacTtsService_SpeakAsync_ErrorTts {
            get {
                return ResourceManager.GetString("MacTtsService_SpeakAsync_ErrorTts", resourceCulture);
            }
        }
        
        public static string MainViewModel_PleaseSetDefaultBoard {
            get {
                return ResourceManager.GetString("MainViewModel_PleaseSetDefaultBoard", resourceCulture);
            }
        }
        
        public static string HistoryViewModel_SaveHistory_Error_saving_history___0_ {
            get {
                return ResourceManager.GetString("HistoryViewModel_SaveHistory_Error_saving_history___0_", resourceCulture);
            }
        }
        
        public static string BoardLoaderService_LoadObfOrObzFileAsync_Nieobsługiwany_typ_pliku__Podaj_plik_z_rozszerzeniem__obf_lub__obz_ {
            get {
                return ResourceManager.GetString("BoardLoaderService_LoadObfOrObzFileAsync_Nieobsługiwany_typ_pliku__Podaj_plik_z_r" +
                        "ozszerzeniem__obf_lub__obz_", resourceCulture);
            }
        }
        
        public static string BoardLoaderService_LoadObfFileAsync_Plik_OBF_jest_pusty_lub_nieprawidłowy_ {
            get {
                return ResourceManager.GetString("BoardLoaderService_LoadObfFileAsync_Plik_OBF_jest_pusty_lub_nieprawidłowy_", resourceCulture);
            }
        }
        
        public static string BoardLoaderService_LoadObfFileAsync_Błąd_podczas_ładowania_pliku_OBF___0___Szczegóły___1_ {
            get {
                return ResourceManager.GetString("BoardLoaderService_LoadObfFileAsync_Błąd_podczas_ładowania_pliku_OBF___0___Szczeg" +
                        "óły___1_", resourceCulture);
            }
        }
        
        public static string BoardLoaderService_LoadObzFileAsync_Error_loading_OBZ_file___0_ {
            get {
                return ResourceManager.GetString("BoardLoaderService_LoadObzFileAsync_Error_loading_OBZ_file___0_", resourceCulture);
            }
        }
        
        public static string BoardLoaderService_ExtractObzArchiveAsync_Skipped_unsafe_entry___0_ {
            get {
                return ResourceManager.GetString("BoardLoaderService_ExtractObzArchiveAsync_Skipped_unsafe_entry___0_", resourceCulture);
            }
        }
        
        public static string BoardLoaderService_ExtractObzArchiveAsync_Access_denied_to_file___0____1_ {
            get {
                return ResourceManager.GetString("BoardLoaderService_ExtractObzArchiveAsync_Access_denied_to_file___0____1_", resourceCulture);
            }
        }
        
        public static string BoardLoaderService_ExtractObzArchiveAsync_Unable_to_overwrite_file___0____1_ {
            get {
                return ResourceManager.GetString("BoardLoaderService_ExtractObzArchiveAsync_Unable_to_overwrite_file___0____1_", resourceCulture);
            }
        }
        
        public static string BoardLoaderService_ExtractObzArchiveAsync_An_error_occurred_while_extracting_file___0____1_ {
            get {
                return ResourceManager.GetString("BoardLoaderService_ExtractObzArchiveAsync_An_error_occurred_while_extracting_file" +
                        "___0____1_", resourceCulture);
            }
        }
        
        public static string HistoryService_LoadHistory_Error_loading_history___0_ {
            get {
                return ResourceManager.GetString("HistoryService_LoadHistory_Error_loading_history___0_", resourceCulture);
            }
        }
        
        public static string OllamaClient_OllamaClient_Connecting_to__0_____ {
            get {
                return ResourceManager.GetString("OllamaClient_OllamaClient_Connecting_to__0_____", resourceCulture);
            }
        }
        
        public static string OllamaClientPrompt {
            get {
                return ResourceManager.GetString("OllamaClientPrompt", resourceCulture);
            }
        }
        
        public static string PictogramService_GetAllPictogramsAsync_Błąd_podczas_deserializacji_pliku_cache___0_ {
            get {
                return ResourceManager.GetString("PictogramService_GetAllPictogramsAsync_Błąd_podczas_deserializacji_pliku_cache___" +
                        "0_", resourceCulture);
            }
        }
        
        public static string PictogramService_GetAllPictogramsAsync_Nieoczekiwany_błąd_podczas_odczytu_pliku_cache___0_ {
            get {
                return ResourceManager.GetString("PictogramService_GetAllPictogramsAsync_Nieoczekiwany_błąd_podczas_odczytu_pliku_c" +
                        "ache___0_", resourceCulture);
            }
        }
        
        public static string PictogramService_GetAllPictogramsAsync_Błąd_podczas_pobierania_piktogramów_z_API___0_ {
            get {
                return ResourceManager.GetString("PictogramService_GetAllPictogramsAsync_Błąd_podczas_pobierania_piktogramów_z_API_" +
                        "__0_", resourceCulture);
            }
        }
        
        public static string PictogramService_DownloadPictogramImageAsync_Nie_udało_się_pobrać_obrazu_piktogramu_o_ID__0___Status_Code___1_ {
            get {
                return ResourceManager.GetString("PictogramService_DownloadPictogramImageAsync_Nie_udało_się_pobrać_obrazu_piktogra" +
                        "mu_o_ID__0___Status_Code___1_", resourceCulture);
            }
        }
        
        public static string PictogramService_DownloadPictogramImageAsync_Błąd_podczas_pobierania_obrazu_piktogramu__0____1_ {
            get {
                return ResourceManager.GetString("PictogramService_DownloadPictogramImageAsync_Błąd_podczas_pobierania_obrazu_pikto" +
                        "gramu__0____1_", resourceCulture);
            }
        }
        
        public static string PictogramService_DownloadPictogramImageAsync_Obraz_piktogramu__0__już_istnieje_w_cache_ {
            get {
                return ResourceManager.GetString("PictogramService_DownloadPictogramImageAsync_Obraz_piktogramu__0__już_istnieje_w_" +
                        "cache_", resourceCulture);
            }
        }
        
        public static string PictogramServiceEmptyArasaac {
            get {
                return ResourceManager.GetString("PictogramServiceEmptyArasaac", resourceCulture);
            }
        }
        
        public static string PictogramServiceErrorArasaac {
            get {
                return ResourceManager.GetString("PictogramServiceErrorArasaac", resourceCulture);
            }
        }
        
        public static string AboutViewModel_AboutViewModel_Error_in_CloseCommand___0_ {
            get {
                return ResourceManager.GetString("AboutViewModel_AboutViewModel_Error_in_CloseCommand___0_", resourceCulture);
            }
        }
        
        public static string ConfigViewModel_InitializeModelsAsync_Error_initializing_models___0_ {
            get {
                return ResourceManager.GetString("ConfigViewModel_InitializeModelsAsync_Error_initializing_models___0_", resourceCulture);
            }
        }
        
        public static string ConfigViewModel_LoadConfiguration_Error_loading_configuration___0_ {
            get {
                return ResourceManager.GetString("ConfigViewModel_LoadConfiguration_Error_loading_configuration___0_", resourceCulture);
            }
        }
        
        public static string ConfigViewModel_SaveConfiguration_Error_saving_configuration___0_ {
            get {
                return ResourceManager.GetString("ConfigViewModel_SaveConfiguration_Error_saving_configuration___0_", resourceCulture);
            }
        }
        
        public static string ObfLoader_LoadObfAsync_No_image_found_for_button_with_ID___0_ {
            get {
                return ResourceManager.GetString("ObfLoader_LoadObfAsync_No_image_found_for_button_with_ID___0_", resourceCulture);
            }
        }
        
        public static string ObfLoader_LoadObfAsync_Missing_label_for_button_with_ID___0_ {
            get {
                return ResourceManager.GetString("ObfLoader_LoadObfAsync_Missing_label_for_button_with_ID___0_", resourceCulture);
            }
        }
    }
}
